// Generated by CoffeeScript 1.9.1
(function() {
  var e;

  module.exports = {
    connection: {
      host: '192.168.178.110',
      port: 9090
    }
  };

  try {
    module.exports = require('./config.local');
  } catch (_error) {
    e = _error;
  }

}).call(this);
