// Generated by CoffeeScript 1.9.1
(function() {
  var TCPConnection, XbmcApi, config, connection, id, ref, xbmcApi;

  ref = require('..'), TCPConnection = ref.TCPConnection, XbmcApi = ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: false
  });

  xbmcApi = new XbmcApi({
    silent: true,
    connection: connection
  });

  id = process.argv[2] || 'QH2-TGUlwu4';

  xbmcApi.player.openYoutube(id);

}).call(this);
